driver:
  name: vagrant
  chef_version: current

provisioner:
  name: chef_zero
  data_bags_path: 'test/fixtures/data_bags'

verifier:
  name: inspec

platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: debian-8.7
    run_list: apt::default
  - name: fedora-25
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: ubuntu-18.04
    run_list: apt::default

suites:
- name: client
  run_list:
    - recipe[ossec::client]
- name: server
  run_list:
    - recipe[ossec::server]
- name: agent_auth
  run_list:
    - recipe[ossec::agent_auth]
  attributes:
    ossec:
      agent_server_ip: 10.0.2.2
- name: authd
  run_list:
    - recipe[ossec::authd]
  driver_config:
    network:
    - ['forwarded_port', { guest: 1514, host: 1514, protocol: 'udp' }]
    - ['forwarded_port', { guest: 1515, host: 1515, protocol: 'tcp' }]
  includes:
    - centos-7.3
    - debian-8.7
